apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shark-app
  template:
    metadata:
      labels:
        app: shark-app
    spec:
      containers:
      - image: imejri/nodejs-image-demo
        name: shark-app
